#!/usr/bin/env python3
"""
Generate Tests - Create Unit Tests and Benchmarks

This tool generates comprehensive unit tests and performance benchmarks
for the target code. It ensures:
1. Semantic preservation (unit tests)
2. Measurable performance improvements (benchmarks)

The "Dual-track Verification" approach:
- Unit tests verify behavior hasn't changed
- Benchmarks measure performance gains
"""

import os
import json
import argparse
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, List
from dataclasses import dataclass


@dataclass
class GeneratedTests:
    """Container for generated tests"""
    unit_test_path: Optional[Path]
    benchmark_path: Optional[Path]
    unit_test_content: str
    benchmark_content: str


def detect_language(file_path: Path) -> str:
    """Detect programming language from file extension"""
    ext_to_lang = {
        '.py': 'python',
        '.js': 'javascript',
        '.ts': 'typescript',
        '.go': 'go',
        '.rs': 'rust',
        '.java': 'java',
        '.cpp': 'cpp',
        '.c': 'c',
        '.rb': 'ruby',
        '.php': 'php',
    }
    return ext_to_lang.get(file_path.suffix.lower(), 'unknown')


def get_function_signatures(file_path: Path, language: str) -> List[Dict[str, str]]:
    """Extract function signatures from source file"""
    import re
    signatures = []

    content = file_path.read_text()

    if language == 'python':
        # Match function definitions
        pattern = r'def\s+(\w+)\s*\(([^)]*)\)'
        for match in re.finditer(pattern, content):
            signatures.append({
                'name': match.group(1),
                'params': match.group(2),
                'full': match.group(0)
            })

    elif language in ['cpp', 'c']:
        # Match C/C++ function definitions
        # Pattern: return_type function_name(params)
        # Handles both declarations and definitions
        pattern = r'(?:^|\n)\s*(?:inline\s+)?(?:static\s+)?(?:const\s+)?[\w:*&<>]+\s+(\w+)\s*\(([^)]*)\)\s*(?:const\s*)?(?:override\s*)?(?:final\s*)?[{;]'
        for match in re.finditer(pattern, content, re.MULTILINE):
            func_name = match.group(1)
            # Skip main and common keywords
            if func_name not in ['main', 'if', 'while', 'for', 'switch', 'catch']:
                signatures.append({
                    'name': func_name,
                    'params': match.group(2),
                    'full': match.group(0)
                })

    elif language in ['javascript', 'typescript']:
        # Match function definitions and arrow functions
        pattern = r'(?:function\s+(\w+)|(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\([^)]*\)\s*=>)'
        for match in re.finditer(pattern, content):
            func_name = match.group(1) or match.group(2)
            signatures.append({
                'name': func_name,
                'params': '',
                'full': match.group(0)
            })

    elif language == 'go':
        # Match Go function definitions
        pattern = r'func\s+(?:\([^)]+\)\s+)?(\w+)\s*\(([^)]*)\)'
        for match in re.finditer(pattern, content):
            signatures.append({
                'name': match.group(1),
                'params': match.group(2),
                'full': match.group(0)
            })

    elif language == 'rust':
        # Match Rust function definitions
        pattern = r'(?:pub\s+)?fn\s+(\w+)\s*(?:<[^>]+>)?\s*\(([^)]*)\)'
        for match in re.finditer(pattern, content):
            signatures.append({
                'name': match.group(1),
                'params': match.group(2),
                'full': match.group(0)
            })

    elif language == 'java':
        # Match Java method definitions
        pattern = r'(?:public|private|protected)?\s*(?:static\s+)?(?:final\s+)?[\w<>[\],\s]+\s+(\w+)\s*\(([^)]*)\)'
        for match in re.finditer(pattern, content):
            func_name = match.group(1)
            if func_name not in ['if', 'while', 'for', 'switch', 'catch']:
                signatures.append({
                    'name': func_name,
                    'params': match.group(2),
                    'full': match.group(0)
                })

    return signatures


def generate_python_unit_test(
    file_path: Path,
    functions: List[Dict[str, str]],
    existing_tests: Optional[Path] = None
) -> str:
    """Generate Python unit tests for the target file"""

    module_name = file_path.stem

    test_code = f'''#!/usr/bin/env python3
"""
Unit Tests for {file_path.name}
Generated by auto-optimizer

CRITICAL: These tests verify semantic preservation during optimization.
Any optimization MUST pass all these tests to be accepted.
"""

import pytest
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from {module_name} import *


class Test{module_name.title()}Basic:
    """Basic functionality tests - MUST ALL PASS"""

'''

    # Generate basic test cases for each function
    for func in functions:
        func_name = func['name']
        if func_name.startswith('_'):
            continue  # Skip private functions

        test_code += f'''    def test_{func_name}_basic(self):
        """Test basic functionality of {func_name}"""
        # TODO: Add specific test cases based on function purpose
        # This is a placeholder - should be customized for actual code
        pass

    def test_{func_name}_edge_cases(self):
        """Test edge cases for {func_name}"""
        # Test with empty input
        # Test with None values
        # Test with boundary conditions
        pass

    def test_{func_name}_error_handling(self):
        """Test error handling for {func_name}"""
        # Test with invalid inputs
        # Test expected exceptions
        pass

'''

    test_code += '''
class Test{module_name.title()}Invariants:
    """Behavioral invariants - These MUST remain unchanged after optimization"""

    def test_output_consistency(self):
        """Verify output doesn't change for same inputs"""
        # Run same input multiple times
        # Verify outputs are identical
        pass

    def test_input_output_types(self):
        """Verify input/output types remain consistent"""
        # Check type preservation
        pass


class Test{module_name.title()}PerformanceBaseline:
    """Performance baseline tests - Used to verify no regression"""

    def test_performance_not_degraded(self):
        """Ensure performance hasn't significantly degraded"""
        import time

        start = time.perf_counter()
        # Call main function with typical input
        elapsed = time.perf_counter() - start

        # Performance should be under some threshold
        # This is a sanity check, not a benchmark
        assert elapsed < 10.0, "Function took too long"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    return test_code


def generate_python_benchmark(
    file_path: Path,
    functions: List[Dict[str, str]]
) -> str:
    """Generate Python benchmark for performance measurement"""

    module_name = file_path.stem

    benchmark_code = f'''#!/usr/bin/env python3
"""
Performance Benchmark for {file_path.name}
Generated by auto-optimizer

This benchmark measures execution time with statistical rigor:
- Multiple iterations to account for variance
- Warmup runs to eliminate cold-start effects
- Various input sizes to test scalability
"""

import time
import statistics
import random
import json
import sys
from pathlib import Path
from typing import Callable, Any, List, Dict

sys.path.insert(0, str(Path(__file__).parent.parent))

from {module_name} import *


def benchmark(
    func: Callable,
    *args,
    iterations: int = 10,
    warmup: int = 3,
    **kwargs
) -> Dict[str, float]:
    """
    Run benchmark with statistical measurements.

    Returns:
        Dict with mean, stdev, min, max, median, p95, p99
    """
    # Warmup runs
    for _ in range(warmup):
        func(*args, **kwargs)

    # Actual measurements
    times = []
    for _ in range(iterations):
        start = time.perf_counter()
        func(*args, **kwargs)
        times.append(time.perf_counter() - start)

    times.sort()

    return {{
        "mean": statistics.mean(times),
        "stdev": statistics.stdev(times) if len(times) > 1 else 0,
        "min": min(times),
        "max": max(times),
        "median": statistics.median(times),
        "p95": times[int(len(times) * 0.95)] if len(times) >= 20 else times[-1],
        "p99": times[int(len(times) * 0.99)] if len(times) >= 100 else times[-1],
        "samples": len(times)
    }}


def generate_test_data(size: int, data_type: str = "random") -> List[Any]:
    """Generate test data of specified size"""
    if data_type == "random":
        return [random.randint(0, 10000) for _ in range(size)]
    elif data_type == "sorted":
        return list(range(size))
    elif data_type == "reverse":
        return list(range(size, 0, -1))
    elif data_type == "duplicates":
        return [random.randint(0, size // 10) for _ in range(size)]
    else:
        return [random.random() for _ in range(size)]


def run_benchmarks() -> Dict[str, Any]:
    """Run all benchmarks and return results"""
    results = {{}}

    # Define test scenarios
    # Modify these based on the actual function being tested
    scenarios = [
        {{"name": "small_random", "size": 100, "type": "random"}},
        {{"name": "medium_random", "size": 1000, "type": "random"}},
        {{"name": "large_random", "size": 10000, "type": "random"}},
        {{"name": "small_sorted", "size": 100, "type": "sorted"}},
        {{"name": "small_reverse", "size": 100, "type": "reverse"}},
    ]

    for scenario in scenarios:
        data = generate_test_data(scenario["size"], scenario["type"])

        # Benchmark the main function
        # Replace 'main_function' with actual function name
        result = benchmark(
            main_function,  # <-- MODIFY THIS
            data,
            iterations=10,
            warmup=3
        )

        results[scenario["name"]] = result

    # Calculate overall metrics
    total_time = sum(r["mean"] for r in results.values())
    results["overall"] = {{"mean": total_time}}

    return results


def main():
    """Run benchmarks and output JSON results"""
    print("Running benchmarks...")
    results = run_benchmarks()

    # Output to stdout and file
    print(json.dumps(results, indent=2))

    # Save to file
    output_path = Path(__file__).parent / ".benchmark_results.json"
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\\nResults saved to {{output_path}}")


if __name__ == "__main__":
    main()
'''

    return benchmark_code


def generate_cpp_unit_test(
    file_path: Path,
    functions: List[Dict[str, str]]
) -> str:
    """Generate C++ unit tests using Google Test framework"""

    header_name = file_path.stem

    test_code = f'''/**
 * Unit Tests for {file_path.name}
 * Generated by auto-optimizer
 *
 * CRITICAL: These tests verify semantic preservation during optimization.
 * Any optimization MUST pass all these tests to be accepted.
 *
 * Requires: Google Test (gtest)
 * Build: g++ -std=c++17 test_{header_name}.cpp -lgtest -lgtest_main -pthread
 */

#include <gtest/gtest.h>
#include "{header_name}.h"
#include <vector>
#include <string>

'''

    # Generate test cases for each function
    for func in functions:
        func_name = func['name']
        test_code += f'''
// Tests for {func_name}
TEST({func_name.capitalize()}Test, BasicFunctionality) {{
    // TODO: Add specific test cases for {func_name}
    // This is a placeholder - should be customized for actual code
    // Example:
    // auto result = {func_name}(input);
    // EXPECT_EQ(result, expected);
}}

TEST({func_name.capitalize()}Test, EdgeCases) {{
    // Test with empty input
    // Test with boundary conditions
    // Test with extreme values
}}

TEST({func_name.capitalize()}Test, InputOutputConsistency) {{
    // Verify output doesn't change for same inputs
    // Run same input multiple times and verify outputs are identical
}}

'''

    test_code += '''
// Main function - gtest provides main, but we can add custom setup here
// int main(int argc, char **argv) {
//     testing::InitGoogleTest(&argc, argv);
//     return RUN_ALL_TESTS();
// }
'''

    return test_code


def generate_cpp_benchmark(
    file_path: Path,
    functions: List[Dict[str, str]]
) -> str:
    """Generate C++ benchmark using Google Benchmark"""

    header_name = file_path.stem

    benchmark_code = f'''/**
 * Performance Benchmark for {file_path.name}
 * Generated by auto-optimizer
 *
 * This benchmark measures execution time with statistical rigor.
 * Requires: Google Benchmark (benchmark)
 * Build: g++ -std=c++17 -O2 benchmark_{header_name}.cpp -lbenchmark -lpthread
 */

#include <benchmark/benchmark.h>
#include "{header_name}.h"
#include <vector>
#include <random>
#include <algorithm>

// Helper to generate test data
std::vector<int> generate_data(size_t size, const std::string& type) {{
    std::vector<int> data(size);
    std::random_device rd;
    std::mt19937 gen(rd());

    if (type == "random") {{
        std::uniform_int_distribution<> dis(0, 10000);
        for (auto& val : data) val = dis(gen);
    }} else if (type == "sorted") {{
        std::iota(data.begin(), data.end(), 0);
    }} else if (type == "reverse") {{
        std::iota(data.rbegin(), data.rend(), 0);
    }}
    return data;
}}

'''

    # Generate benchmark functions
    for func in functions:
        func_name = func['name']
        benchmark_code += f'''
// Benchmark for {func_name}
static void BM_{func_name}_Small(benchmark::State& state) {{
    auto data = generate_data(100, "random");
    for (auto _ : state) {{
        auto copy = data;
        {func_name}(copy);
        benchmark::DoNotOptimize(copy);
    }}
}}
BENCHMARK(BM_{func_name}_Small);

static void BM_{func_name}_Medium(benchmark::State& state) {{
    auto data = generate_data(1000, "random");
    for (auto _ : state) {{
        auto copy = data;
        {func_name}(copy);
        benchmark::DoNotOptimize(copy);
    }}
}}
BENCHMARK(BM_{func_name}_Medium);

static void BM_{func_name}_Large(benchmark::State& state) {{
    auto data = generate_data(10000, "random");
    for (auto _ : state) {{
        auto copy = data;
        {func_name}(copy);
        benchmark::DoNotOptimize(copy);
    }}
}}
BENCHMARK(BM_{func_name}_Large);

'''

    benchmark_code += '''
BENCHMARK_MAIN();
'''

    return benchmark_code


def generate_tests_for_file(
    file_path: Path,
    output_dir: Path,
    force: bool = False
) -> GeneratedTests:
    """
    Generate unit tests and benchmarks for a source file.

    Args:
        file_path: Path to source file
        output_dir: Directory to write generated tests
        force: Overwrite existing tests

    Returns:
        GeneratedTests object with paths and content
    """
    language = detect_language(file_path)
    functions = get_function_signatures(file_path, language)

    # Create output directories
    unit_test_dir = output_dir / ".unit_tests"
    benchmark_dir = output_dir / ".perf_tests"
    unit_test_dir.mkdir(exist_ok=True)
    benchmark_dir.mkdir(exist_ok=True)

    # Determine file extensions based on language
    if language in ['cpp', 'c']:
        test_ext = '.cpp'
    elif language in ['javascript', 'typescript']:
        test_ext = '.test.js' if language == 'javascript' else '.test.ts'
    elif language == 'go':
        test_ext = '_test.go'
    elif language == 'rust':
        test_ext = '_test.rs'
    elif language == 'java':
        test_ext = 'Test.java'
    else:
        test_ext = '.py'

    # Generate unit tests
    if language in ['cpp', 'c']:
        unit_test_path = unit_test_dir / f"test_{file_path.stem}{test_ext}"
        unit_test_content = generate_cpp_unit_test(file_path, functions)
    elif language == 'python':
        unit_test_path = unit_test_dir / f"test_{file_path.stem}{test_ext}"
        unit_test_content = generate_python_unit_test(file_path, functions)
    else:
        unit_test_path = unit_test_dir / f"test_{file_path.stem}{test_ext}"
        unit_test_content = f"// Unit tests for {file_path.name}\n// Language: {language}\n// TODO: Generate tests for this language\n"

    if force or not unit_test_path.exists():
        unit_test_path.write_text(unit_test_content)

    # Generate benchmarks
    if language in ['cpp', 'c']:
        benchmark_path = benchmark_dir / f"benchmark_{file_path.stem}{test_ext}"
        benchmark_content = generate_cpp_benchmark(file_path, functions)
    elif language == 'python':
        benchmark_path = benchmark_dir / f"benchmark_{file_path.stem}{test_ext}"
        benchmark_content = generate_python_benchmark(file_path, functions)
    else:
        benchmark_path = benchmark_dir / f"benchmark_{file_path.stem}{test_ext}"
        benchmark_content = f"// Benchmark for {file_path.name}\n// Language: {language}\n// TODO: Generate benchmark for this language\n"

    if force or not benchmark_path.exists():
        benchmark_path.write_text(benchmark_content)

    return GeneratedTests(
        unit_test_path=unit_test_path,
        benchmark_path=benchmark_path,
        unit_test_content=unit_test_content,
        benchmark_content=benchmark_content
    )


def verify_tests_run(test_path: Path) -> tuple[bool, str]:
    """Verify that generated tests can run"""
    try:
        result = subprocess.run(
            ["python", "-m", "pytest", str(test_path), "-v", "--collect-only"],
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode == 0:
            return True, "Tests collected successfully"
        else:
            return False, result.stderr
    except Exception as e:
        return False, str(e)


def main():
    parser = argparse.ArgumentParser(
        description="Generate unit tests and benchmarks for source files"
    )
    parser.add_argument(
        "target",
        type=Path,
        help="Source file or directory to generate tests for"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=Path.cwd(),
        help="Output directory for generated tests"
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing test files"
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify generated tests can run"
    )

    args = parser.parse_args()

    target = args.target.resolve()
    output_dir = args.output.resolve()

    if target.is_file():
        files = [target]
    elif target.is_dir():
        # Find source files of multiple languages
        files = []
        for ext in ['*.py', '*.cpp', '*.c', '*.js', '*.ts', '*.go', '*.rs', '*.java']:
            files.extend(target.glob(f'**/{ext}'))
        files = [f for f in files if not any(p.startswith('.') for p in f.parts)]
    else:
        print(f"Error: {target} does not exist")
        return 1

    print(f"Generating tests for {len(files)} file(s)...")

    for file_path in files:
        print(f"\nProcessing: {file_path}")

        generated = generate_tests_for_file(file_path, output_dir, args.force)

        print(f"  Unit tests: {generated.unit_test_path}")
        print(f"  Benchmark: {generated.benchmark_path}")

        if args.verify:
            success, msg = verify_tests_run(generated.unit_test_path)
            print(f"  Verification: {'✓' if success else '✗'} {msg}")

    print("\nDone!")
    return 0


if __name__ == "__main__":
    exit(main())
